### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by juhakaup** [shomarov/ohte-2020#1]
Repo ladattu Pe 24.4. 9:00

Yleisilmeeltään koodi on siistiä ja selkeästi jaoteltua.

Nykyisessä muodossaan UI luokka ei näytä siältävän toisteista koodia, mutta nyt implementoitu toiminnallisuus on aika spesifisesti sidottu kyseiseen toimintoon. Ilmeisesti samoja toimintoja voi kuitenkin suorittaa sekä valikosta että kontekstimenusta.
Olet varmaan näin ajatellut tekeväsikin, mutta toimintoja voisi jakaa metodeihin joita kutsutaan noista eventtien lambdoista, jolloin eri paikoista tehdyt toiminnot saa helposti tehtyä koodissa. 

Toinen asia mitä mietin, on toimintojen tämänhetkinen toteutus. Esimerkiksi UI luokassa oleva deleteFiles metodi käskyttää suoraan photoFileDao:ta.
Mistä tulee mieleen, että mikä on PhotoFileServicen rooli? Ajatuksenani on että jos UI-luokka kirjoitettaisiin kokonaan uusiksi, niin säilyisikö sovelluksen toimintalogiikka samana sen myötä.

Ohjelma tuntuu löytävän duplikaatteja ja niiden poistaminen onnistuu. Poistamisen jälkeen lista ei näytä päivittyvän, vaikka itse tiedosto häviääkin.

Duplicate scan -näkymän avautuminen omaan ikkunaansa oli aluksi hieman hämäävää, ikkuna on samankokoinen ja samassa kohtaa kun varsinainen näkymä joten en ymmärtänyt sen olevan ponnahdusikkuna.
Tämäntyyppisille elementeille tutut OK, Cancel... tms -napit selkeyttäisivät asiaa. Tai sitten näkymän voisi koittaa pitää ohjelman varsinaisessa näkymässä, mikä olisi ehkä hieman modernimpi lähestymistapa.

Muuten ohjelma näyttää ihan vakuuttavalta. 
Ei muuta kun työn iloa viimeistelyyn.

**Comment by shomarov** [comment]
Kiitos katselmoinnista! Samaa mieltä kaikista asioista, ja näin kuvaamallasi tavallakin suunnittelenkin tehdä. Toivottavasti aika riittää.
